### ISSUE TITLE
GCP/k8s issues | Traefik workarounds

### ISSUE THREAD

**Issue by hradaideh** [tpboudreau/l6s#3]
- external mysql is no configured for the prepare-database script
- add this to secrets.yaml

```
  mysql_host: {{ .Values.librenmsServices.mysql.external.address | b64enc }}
```

- and this to the prepare container

```
        - name: LIBRENMS_MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: application
              key: mysql_host
```

- GCP Cloud SQL is not compatible with your check-mysql python script
- there is no toleration/node selector defined in the charts
- this will allow your ingress to run with Traefik

```
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
```

- plus the LIBRENMS_BASE_URL should have the ability to choose between https and http from the values file

```
  LIBRENMS_BASE_URL: {{ coalesce .Values.Application.baseURL ( cat "https://" .Values.Application.ingressHost .Values.Application.ingressPath | nospace ) | quote }}

```
